FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
RUN apk add --no-cache wget
RUN addgroup -S nextjs && adduser -S nextjs -G nextjs
COPY package.json package-lock.json* ./
RUN npm ci --include=dev
COPY . .
RUN npm run build
USER nextjs
EXPOSE 3000
CMD ["npm", "run", "start"]
