server {
    listen 80;
    server_name produmantech.ru www.produmantech.ru;

    location / {
        proxy_pass http://frontend-zkgwgs8k8wk0404wwg8css4k-194519338467:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name cms.produmantech.ru;

    location / {
        proxy_pass http://cms-zkgwgs8k8wk0404wwg8css4k-194519312371:1337;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
