server {
    listen 80;
    server_name produmantech.ru www.produmantech.ru;

    location / {
        return 301 https://produmantech.ru$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name produmantech.ru;

    ssl_certificate /etc/letsencrypt/live/produmantech.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/produmantech.ru/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://frontend-zkgwgs8k8wk0404wwg8css4k-194519338467:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name cms.produmantech.ru;

    location / {
        return 301 https://cms.produmantech.ru$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name cms.produmantech.ru;

    ssl_certificate /etc/letsencrypt/live/produmantech.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/produmantech.ru/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://cms-zkgwgs8k8wk0404wwg8css4k-194519312371:1337;
        proxy_http_version 1.1;
        proxy_set_header Host localhost:1337;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }
}

server {
    listen 80;
    server_name media.produmantech.ru;

    location / {
        return 301 https://media.produmantech.ru$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name media.produmantech.ru;

    ssl_certificate /etc/letsencrypt/live/produmantech.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/produmantech.ru/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Cache imgproxy responses at nginx level
    proxy_cache_valid 200 7d;
    add_header X-Cache-Status $upstream_cache_status;

    location / {
        proxy_pass http://imgproxy-zkgwgs8k8wk0404wwg8css4k:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
